### PR TITLE
Fix compilation with newest Ecto 1.1.x

### PR DESCRIPTION
**Pull request by iancanderson**
The `put_meta/2` function was moved from `Ecto.Model` to top-level `Ecto` module.

See https://github.com/elixir-ecto/ecto/commit/b33075098376b75008b24a115652c6c7cbd71feb

### CODE REVIEW

**Comment by iancanderson** [comment]
This should be considered a work in progress - still working out some issues

**Comment by Dania02525** [comment]
Thank you for the help- do you think we should keep the pre ecto 2.0 version as a branch, for people to add into older projects or should we just end up updating the main branch for 2.0?

**Comment by iancanderson** [comment]
My recommendation would be to start releasing versions of the package via https://hex.pm/docs/publish. Then you could have a a version cutoff where you add support for a new version of ecto / remove support for older versions.

**Comment by iancanderson** [comment]
Going to close this in favor of a more focused PR that doesn't try to be compatible with newer versions of postgrex

**Pull request closed without merging**
